### ISSUE TITLE
Management Command Issue?

### ISSUE THREAD

**Issue by michealjroberts** [sabricot/django-elasticsearch-dsl#264]
Not sure what is exactly going on, but using a standard `docker-compose` configuration file, and following the very basic of tutorials in the official docs, the management command for `search_index` is not available when utilising `docker-compose exec web python manage.py --help`...

requirements.txt contains:
`elasticsearch==7.6.0`
`elasticsearch-dsl==7.1.0`

My elasticsearch service in docker-compose:
```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
```
